name: BlockReplacerSpout
main: me.estyx.BlockReplacerSpout.BlockReplacerSpout
version: 0.1
author: estyx
description: Replace blocks with redstone and signs, for Spout custom blocks

permissions:
    blockreplacerspout.*:
        default: op
        description: Gives access to all functions
        children:
            blockreplacerspout.create: true
            blockreplacerspout.use: true
    blockreplacerspout.create:
        default: op
        description: Can create a replacer sign.
    blockreplacerspout.use:
        default: true
        description: Can use a replacer sign by right-click